name: ExtrapolaTED
channels:
  - pytorch
  - defaults  # Remove nvidia channel
dependencies:
  - python=3.10
  - pytorch  # This will automatically install the CPU version on osx-arm64
  - torchvision
  - torchaudio
  - numpy
  - pip
  - pip:
    - uform
    - usearch
    - simsimd
    - stringzilla
    - datasets
    - transformers
    - mwparserfromhell
    - apache_beam
    - ipykernel
    - jupyter
    - ipywidgets
    - pandas
    - pillow
    - pyarrow
    - requests
